NDSR-1048: Fix fetcher metrics.
CasperLabs/casper-node pull request #1249
Opened 2021-03-30 14:02 UTC by goral09

https://casperlabs.atlassian.net/browse/NDRS-1048

This PR fixes a bug where `Fetcher` would incorrectly count the number of requests that time out. Previously, we would consider every request made as timed out as `TimeoutPeer` events are not canceled if the original fetch request had completed successfully. 

### Note: ###
I am not happy with the fact that I had to put `metrics` method into the `ItemFetcher` trait but b/c of how the abstractions are written and the fact that the whole logic/information about whether the request really timed-out or not is hidden inside the `signal` method (that is implemented on the `ItemFetcher` trait), there was no easy way to extract this information without a major rewrite. I've spent a lot of time on this already so I went for a correct solution right now.

2021-03-31 17:24 UTC, xcthulhu requested changes
This isn't compatible with NDRS-1001, so we have to rethink how we are going to do this...

2021-03-31 18:23 UTC, goral09 commented
> This isn't compatible with NDRS-1001, so we have to rethink how we are going to do this...

What is NDRS-1001? I can't see PR for it. Also, this isn't changing the functionality, it's just fixing a bug.

2021-03-31 20:58 UTC, goral09 commented
> This isn't compatible with NDRS-1001, so we have to rethink how we are going to do this...

Can you explain why _this_ PR makes the `Fetcher` incompatible with NDRS-1001?

2021-04-01 15:05 UTC, xcthulhu commented
I've incorporated these changes into  #1080, closing in favour of that PR.

2021-04-01 15:05 UTC, closed without merging