NDRS-521 remove unbond_purse arg in withdraw_bid contract
CasperLabs/casper-node pull request #388
Opened 2020-10-17 15:41 UTC by sacherjj

Removing the unbond_purse arg to allow casper-client 1.4.0 to use this contract.
This will be undone once the fix of client for NDRS-521 is complete.

2020-10-17 15:50 UTC, sacherjj commented
Accidentally based on release rather than master.  Cleaned up.

2020-10-19 12:32 UTC, Fraser999 reviewed
Looks like a couple of the tests need updated/disabled until this is reverted.

Otherwise looks good to me.

2020-10-21 20:32 UTC, EdHastingsCasperLabs commented
Don't apply this (or other similar changes to these contracts) to master; the contracts are correct. There is a bug ticket to fix the client to handle Optional args.

2020-10-21 20:33 UTC, EdHastingsCasperLabs requested changes
This may be applied to a feature branch until client-rs is patched, if desired. But it should not be applied to master.

2020-10-28 20:57 UTC, sacherjj commented
client resolved, no longer needed.

2020-10-28 20:57 UTC, closed without merging