NO-TICK: Do not accept endorsements created by equivocators.
CasperLabs/casper-node pull request #470
Opened 2020-10-31 11:16 UTC by goral09

1. Remove an entry from `complete_endorsements` when we detect that its creator has equivocated.
2. Do not accept endorsements created by faulty validators.

2020-10-31 13:58 UTC, afck requested changes
I'm not sure it's safe to do this.

E.g. if you send me a vote A that depends on endorsements for B, and then on my request you send me what you believe is a complete set of endorsements for B, then I would remove from those incoming endorsements all those whose creators I know are faulty, even if you do not. That might turn the complete into an incomplete set, and fail to satisfy the dependency.

I think it would be better to first implement the whole endorsement/spam protection story, and then consider fork spam as a separate issue. ([HWY-160](https://casperlabs.atlassian.net/browse/HWY-160))

2020-10-31 14:30 UTC, goral09 commented
> E.g. if you send me a vote A that depends on endorsements for B, and then on my request you send me what you believe is a complete set of endorsements for B, then I would remove from those incoming endorsements all those whose creators I know are faulty, even if you do not. That might turn the complete into an incomplete set, and fail to satisfy the dependency.

Yes, that's correct. Paper says that vote is endorsed if >= 2/3 of honest validators endorse it. I will try to come up with an example.

2020-10-31 21:33 UTC, closed without merging

2020-11-01 01:58 UTC, goral09 commented
I think it's _correct_ to do this (in a sense that it won't break the safety of the protocol) but not a good idea since it would require an additional mechanism for asking for endorsements – since we might remove some endorsements from the _previously-complete_ set – which we don't have and don't want to.

It also doesn't matter what dishonest validators endorse as long as it's not more than 2/3 of the stake. In which case we're doomed anyway.

2020-11-01 09:27 UTC, afck commented
Maybe… I still have some concerns, though.
Let's have a discussion about it first, as part of (HWY-160)[https://casperlabs.atlassian.net/browse/HWY-160].