Ndrs 575 add documentation rpc
CasperLabs/casper-node pull request #533
Opened 2020-11-13 15:57 UTC by darthsiroftardis

REF: https://casperlabs.atlassian.net/browse/NDRS-575

I have added a subcommand called `docs_get_rpcs` that displays all currently supported RPC, with documentation on each RPC. I have attached a text file to this PR with the sample output to be reviewed. I asked both Mateusz and Henry to join in the review as there maybe some inconsistencies in the representation of certain RPCs that I may not be aware of. 

*Sample Output*
[ndrs_575_output.txt](https://github.com/CasperLabs/casper-node/files/5537920/ndrs_575_output.txt)

2020-11-13 15:59 UTC, goral09 commented
I haven't used the RPC at all, nor have I written the code. I think it would take too much time to provide and valuable input. I would like to unassign myself from the review.

2020-11-13 21:59 UTC, Fraser999 requested changes
Please try and not have `cargo fmt` runs as separate commits.  You should be able to set up your IDE or have a post-commit hook to avoid this.  Also, you should always run `make check-rs` before creating a PR or committing to a PR to try and cut down on the number of commits and failed CI runs.

Normally `lazy_static` instances are defined at the top of a source file, in the same way that `const` values are.  I'd be fine with these living inside their respective `doc_example` methods though, e.g.

```rust
impl DocExample for NodeId {
    fn doc_example() -> &'static Self {
        lazy_static! {
            static ref NODE_ID: NodeId =
                NodeId::Tls(KeyFingerprint::from([1u8; KeyFingerprint::LENGTH]));
        }
        &*NODE_ID
    }
}
```

There are two major blockers to merging this PR:
1. The docs RPC response is missing details for the `state_get_item` RPC
2. The response needs to be constant across sessions and nodes.  Please at least check this is true for sessions before asking for re-review.  Run a vault, output the response via a client to a file, restart the vault, output to a different file, and finally check the files are identical (modulo the RPC ID unless you specify one via the command line).

2020-11-17 17:29 UTC, darthsiroftardis commented on node/src/components/chainspec_loader.rs
> +    static ref CHAINSPECINFO: ChainspecInfo = ChainspecInfo {
Renamed

2020-11-17 17:29 UTC, darthsiroftardis commented on node/src/components/rpc_server/rpcs/docs.rs
> +use casper_types::U512;
Moved

2020-11-17 17:31 UTC, darthsiroftardis commented on node/src/components/rpc_server/rpcs/docs.rs
> +
Changed it one blank line

2020-11-17 17:32 UTC, darthsiroftardis commented on node/src/components/rpc_server/rpcs/docs.rs
> +            rpcs:  vec![],
Removed extra whitespace

2020-11-17 19:28 UTC, darthsiroftardis commented on node/src/components/rpc_server/rpcs/docs.rs
> +           let deploy = Deploy::doc_example();
Formatted separately, and re-inserted back into `lazy_static`

2020-11-17 19:37 UTC, darthsiroftardis commented on node/src/components/rpc_server/rpcs/docs.rs
> +                "Creates a Deploy and sends it to the network for execution.",
I am reusing the documentation in `client/lib.rs`, should I change it anyway

2020-11-17 19:41 UTC, darthsiroftardis commented on client/lib/lib.rs
> +/// Retrieves all currently supported RPCS.
Added additional documentation within the client

2020-11-17 19:49 UTC, darthsiroftardis commented on client/src/docs.rs
> +mod get;
Treated similar to `get_auction_info`

2020-11-17 19:53 UTC, darthsiroftardis commented on node/src/components/rpc_server/rpcs/docs.rs
> +/// A trait to generate static hardcode representations of data structures to present for RPC calls.
Changed documentation

2020-11-17 19:54 UTC, darthsiroftardis commented on node/src/components/rpc_server/rpcs/docs.rs
> +    /// Generate a hardcoded, possibly invalid example of the requested data structure.
Changed documentation

2020-11-17 19:55 UTC, darthsiroftardis commented on node/src/components/rpc_server/rpcs/docs.rs
> +    #[allow(clippy::too_many_arguments)]
Removed

2020-11-17 19:55 UTC, darthsiroftardis commented on node/src/components/rpc_server/rpcs/docs.rs
> +            requirement: String::from("params must be presenet"),
Corrected spelling

2020-11-17 20:02 UTC, darthsiroftardis commented on node/src/components/rpc_server/rpcs/docs.rs
> +    request_params: Option<RequestParams>,
Removed `Option` and changed to simply, `RequestParams`

2020-11-17 20:05 UTC, darthsiroftardis commented on node/src/crypto/asymmetric_key.rs
> +impl DocExample for SecretKey {
Changed it a `doc_example` that results a consistent value across multiple node sessions

2020-11-17 20:05 UTC, darthsiroftardis commented on node/src/crypto/hash.rs
> +
Yes, changed accordingly

2020-11-17 20:10 UTC, darthsiroftardis commented on node/src/types/block.rs
> +    static ref FINALIZEDBLOCK: FinalizedBlock = {
Renamed

2020-11-17 20:10 UTC, darthsiroftardis commented on node/src/types/block.rs
> +    static ref ERAEND: EraEnd = {
Renamed

2020-11-17 20:10 UTC, darthsiroftardis commented on node/src/types/block.rs
> +        let timestamp = Timestamp::now();
Constant values are being generated across multiple node sessions

2020-11-17 20:11 UTC, darthsiroftardis commented on node/src/types/deploy.rs
> +    static ref STORECONTRACTNAME: ExecutableDeployItem = {
Removed `lazy_static` for `STORED_CONTRACT_BY_NAME`

2020-11-17 20:13 UTC, darthsiroftardis commented on node/src/types/deploy.rs
> +    static ref MODULEBYTES: ExecutableDeployItem = {
Removed `lazy_static`

2020-11-17 21:25 UTC, closed without merging

2020-11-17 21:26 UTC, darthsiroftardis commented
PR Closed, refer to a PR for [NDRS-591](https://github.com/CasperLabs/casper-node/pull/533/commits/8cf853b14d6610955be8b1519240a56af16d9ff5)

2020-11-18 00:29 UTC, Fraser999 commented on node/src/components/rpc_server/rpcs/docs.rs
> +                "Creates a Deploy and sends it to the network for execution.",
Don't worry about changing this now.  We'll give these all an overhaul once we decide upon a consistent style.  We'll use the modified "summary" strings from the handwritten doc we created.