NDRS-473: Optimize bytes/array serialization without nightly
CasperLabs/casper-node pull request #563
Opened 2020-11-20 15:47 UTC by mpapierski

Ref: https://casperlabs.atlassian.net/browse/NDRS-473

One step forward for getting stable support. Removes all default impls, and where applicable `Vec<u8>`/`[u8; N]` serialiation/deserialization is done through newtypes wrapper where it is applied at type level (i.e. replaced `Vec<u8>` with `Bytes`. Array serialization/deserialization is limited only to u8 and this also reflects in `CLType` where `FixedList(type, size)` is replaced with `ByteArray(size)`.

_Benchmarks on the way_

2020-11-20 16:08 UTC, dwerner commented on execution_engine/src/core/runtime/mod.rs
> +        CLType::ByteArray(_) => Ok(vec![]),
:+1:

2020-11-20 16:26 UTC, dwerner commented on execution_engine/src/storage/trie/mod.rs
> +            let mut result: MaybeUninit<PointerBlockArray> = MaybeUninit::uninit();
I'm having a hard time understanding this at first glance - would it be possible to add a comment that describes the justification for using `MaybeUninit`?

2020-11-20 16:40 UTC, dwerner commented on types/src/gens.rs
> +        // [any::<u64>(); 32].prop_map(|x| CLValue::from_t(x).expect("should create CLValue")),
If it's intended to leave this commented out, perhaps a comment as to why?

2020-11-20 16:42 UTC, dwerner approved these changes
Nice job, cleans up a lot of code, left a couple of nitpicks about commenting some areas that weren't clear to me. Do you have any criterion/bench results showing the speedup?

2020-11-21 00:18 UTC, henrytill reviewed
Code itself looks good, a few nits. 

However, my benchmark results do show some not-insignificant regressions, along with some improvements.  A mixed bag...
https://gist.github.com/henrytill/03ff03322c8aa26c017f556f65d83857

Do we still have the transfer benchmarks?  They might be helpful in helping us assess the real-world performance impact of these changes.  I was under the impression they would be here, but don't seem to be included anymore.

cc @EdHastingsCasperLabs

2020-11-21 00:54 UTC, henrytill commented
> Do we still have the transfer benchmarks? They might be helpful in helping us assess the real-world performance impact of these changes. I was under the impression they would be here, but don't seem to be included anymore.

Figured it out and got some transfer bench runs:
https://gist.github.com/henrytill/03ff03322c8aa26c017f556f65d83857#file-transfer_benchmark-txt

:+1:

2020-11-21 00:54 UTC, henrytill approved these changes

2020-11-23 11:00 UTC, Fraser999 requested changes
The following comments on the previous PR have not been addressed:
* https://github.com/CasperLabs/casper-node/pull/526#discussion_r522955722
* https://github.com/CasperLabs/casper-node/pull/526#discussion_r522920861
* https://github.com/CasperLabs/casper-node/pull/526#discussion_r522975422
* https://github.com/CasperLabs/casper-node/pull/526#discussion_r522979787

2020-11-23 14:35 UTC, Fraser999 approved these changes

2020-11-23 15:22 UTC, mpapierski commented
bors r+

2020-11-23 15:53 UTC, merged