EE-1120: Slash unbonding delegators.
CasperLabs/casper-node pull request #618
Opened 2020-12-04 18:03 UTC by mpapierski

Ref: https://casperlabs.atlassian.net/browse/EE-1120

Adds a clause to the slashing logic so delegators present in bids entry for given slashed validator are collected, and then also removed from unbonding purses for given slashed validator.

2020-12-04 18:27 UTC, henrytill reviewed
I think we need new slash tests exercising this logic.

2020-12-07 21:22 UTC, henrytill reviewed
Overall looking good.  A couple suggestions and questions.

With regards to the test, these may seem like nits, but I'd like to see more consistency with regards to comments and formatting.  These auction tests are being read closely by several people (possibly third parties), so it is important that they be as clean as possible.

2020-12-07 21:22 UTC, henrytill commented on grpc/tests/src/test/regression/ee_1120.rs
> +    // compare bids after slashing validator 2
```suggestion
    // Compare bids after slashing validator 2
```

2020-12-07 21:22 UTC, henrytill commented on grpc/tests/src/test/regression/ee_1120.rs
> +    // NOTE: Validator2's bid on Validator1 wasn't slashed.
```suggestion
    // validator 2's delegation bid on validator 1 was not slashed.
```

2020-12-07 21:22 UTC, henrytill commented on grpc/tests/src/test/regression/ee_1120.rs
> +    // NOTE: As mentioned above Validator2's unbonding purse on Validator1 wasn't slashed
```suggestion
    // validator 2's delegation unbond from validator 1 was not slashed
```

2020-12-07 21:22 UTC, henrytill commented on grpc/tests/src/test/regression/ee_1120.rs
> +    // validators he delegates to
```suggestion
    // delegator 1 had a delegation unbond slashed for validator 2's behavior.
    // delegator 1 still has an active delegation unbond from validator 2.
```

2020-12-07 21:22 UTC, henrytill commented on grpc/tests/src/test/regression/ee_1120.rs
> +    // slash validator1 to clear both bids and unbonding purses
```suggestion
    // slash validator 1 to clear remaining bids and unbonding purses
```

2020-12-07 21:22 UTC, henrytill commented on grpc/tests/src/test/regression/ee_1120.rs
> +    // sanity check of the system before undelegating
```suggestion
    // Ensure that initial bid entries exist for validator 1 and validator 2
```

2020-12-07 21:22 UTC, henrytill commented on types/src/auction.rs
> +            // Clean up bids for given validator and save up assigned delegators
```suggestion
            // Remove bid for given validator, saving its delegators
```

2020-12-07 21:22 UTC, henrytill commented on types/src/auction.rs
> +            // Clean up unbonding entry for given validator
```suggestion
            // Update unbonding entries for given validator
```

2020-12-07 21:22 UTC, henrytill commented on types/src/auction.rs
> +                    // to quashed bids of validator.
```suggestion
                    // Retain all entries where this validator is delegating to another validator.
```

(if my assumptions in the other comment are correct)

2020-12-07 21:22 UTC, henrytill commented on types/src/auction.rs
>          // call reduce total supply
Remove this line, it's redundant

2020-12-08 13:05 UTC, mpapierski commented on types/src/auction.rs
>          // call reduce total supply
Did this

2020-12-08 13:05 UTC, mpapierski commented on grpc/tests/src/test/regression/ee_1120.rs
> +static VALIDATOR_2_ADDR: Lazy<AccountHash> = Lazy::new(|| VALIDATOR_2.into());
Done that

2020-12-08 17:22 UTC, henrytill requested changes

2020-12-08 17:22 UTC, henrytill commented on types/src/auction.rs
>              if let Some(unbonding_list) = unbonding_purses.get_mut(&validator_public_key) {
Discussed offline: need to change this to `remove`.

2020-12-08 17:22 UTC, henrytill commented on types/src/auction.rs
> +                        && !orphaned_delegators.contains(unbonding_purse.unbonder_public_key());
Addressed offline, my understanding did not reflect changes to unbonding purse structure.

2020-12-09 17:12 UTC, henrytill approved these changes

2020-12-09 17:12 UTC, henrytill commented on types/src/auction.rs
> +                unbonding_purses_modified = true;
The symmetry between how we now handle `bids` and `unbonding_purses` is very reassuring!

2020-12-09 17:14 UTC, mpapierski commented
bors r+

2020-12-09 17:43 UTC, merged