ECO-790: serialized clType as well
CasperLabs/casper-node pull request #701
Opened 2021-01-04 15:27 UTC by AbnerZheng

I need clType as well to deserialized CLValue.

2021-01-05 12:32 UTC, Fraser999 requested changes
I created https://github.com/CasperLabs/casper-node/pull/706 to fix the deserialization of CLValue to match your changes here.

I'm not quite clear why we really need to encode the `CLType` into the serialized bytes of the JSON representation to be honest.  I'd be keen to understand the rationale for this, and I'd also like @henrytill and @mpapierski to see this, since the EE is heavily involved in the `CLValue` (although not so much as a JSON value).

If this PR goes ahead, it does affect the library's interface, hence I added @momipsl as a reviewer, and I'm assuming that you already discussed this change with @zie1ony

2021-01-05 13:03 UTC, AbnerZheng commented
The reason why I need to encode `clType` information is that, I am trying to deserialize the `serialized_bytes` into CLValue, I don't use the `parsed_json_value` directly.

2021-01-05 13:11 UTC, Fraser999 commented
> The reason why I need to encode clType information is that, I am trying to deserialize the serialized_bytes into CLValue, I don't use the parsed_json_value directly.

So, when you get a JSON value representing a `CLValue`, it contains the fields `cl_type` and `serialized_bytes`.  To turn that into a true `CLValue`, you should be able to assign the `cl_type` directly to the `cl_type` member of the `CLValue`, and the `serialized_bytes` just need to be decoded from hex and assigned to the `bytes` member of the `CLValue`.

Would that work for you?  It seems like it should be simpler and more efficient.

2021-01-06 00:07 UTC, henrytill commented
Agree with @Fraser999 here, seems like this shouldn't be necessary and that his proposed alternative approach should solve the problem.

2021-01-06 07:31 UTC, AbnerZheng commented
> > The reason why I need to encode clType information is that, I am trying to deserialize the serialized_bytes into CLValue, I don't use the parsed_json_value directly.
> 
> So, when you get a JSON value representing a `CLValue`, it contains the fields `cl_type` and `serialized_bytes`. To turn that into a true `CLValue`, you should be able to assign the `cl_type` directly to the `cl_type` member of the `CLValue`, and the `serialized_bytes` just need to be decoded from hex and assigned to the `bytes` member of the `CLValue`.
> 
> Would that work for you? It seems like it should be simpler and more efficient.

No, I don't think it is a good idea. 
I guess you want me to create a struct for ClValue:

```js
class CLValue {
   cl_type: string,
   json_value: any,
   bytes: Bytes
}
```
But how to represent the complex `clType`, like List<string>, in the string? Finally, I need another parser to understand complex types. So why not deserialize the bytes directly into CLValue. Here is what I have now:

```js
describe('StoredValue', () => {
  it('storeValue', async () => {
    const casperService = new CasperServiceByJsonRPC(
      'http://192.168.2.166:40101/rpc'
    );
    const latestBlockInfo = await casperService.getLatestBlockInfo();
    const stateRootHash = latestBlockInfo.block!.header.state_root_hash;
    const clValue = await casperService.getBlockState(
      stateRootHash,
      'uref-e742b9a5b05e8de4a4bea55dd672c8046429ff76edcd6abf4afe7401eed8e474-000',
      []
    );
    const u512 = clValue.CLValue?.value?.value as U512;
    const mapCLValue = CLValue.map([
      { key: CLTypedAndToBytesHelper.string('purse'), value: u512 }
    ]);
    console.log(mapCLValue);
  });
});

```

I could easily to build composed type(map) from the parsed stored value.

2021-01-26 20:24 UTC, closed without merging