NDRS-706: Provide JSON versions of Contract and ContractPackage
CasperLabs/casper-node pull request #718
Opened 2021-01-06 20:45 UTC by darthsiroftardis

REF: https://casperlabs.atlassian.net/browse/NDRS-706

Added `Contract` and `ContractPackage` struct to a new `contracts.rs` module inside the json compatibility module.

2021-01-07 12:11 UTC, Fraser999 requested changes
A good start, but a couple of changes required to complete this work.

I'd also like to see an example of a JSON-encoded version of a `Contract` and `ContractPackage` before approving this.

2021-01-07 20:06 UTC, henrytill commented on node/src/types/json_compatibility/contracts.rs
> +    ContractPackageHash, ContractWasmHash, EntryPoint, NamedKey, ProtocolVersion, URef,
I'm fine with @Fraser999's suggestion.  While I had been exploring some options in the space, I ultimately shelved that work in favor of continuing our current approach.

2021-01-13 23:23 UTC, darthsiroftardis commented on types/src/protocol_version.rs
> +// TODO - remove once schemars stops causing warning.
Used Version as requested

2021-01-13 23:24 UTC, darthsiroftardis commented on node/src/types/json_compatibility/contracts.rs
> +    ContractPackageHash, ContractWasmHash, EntryPoint, NamedKey, ProtocolVersion, URef,
@Fraser999 I tried wrapping the new types in `key.rs` but the hastle of refactoring was far too much. Multiple tests were breaking and I was unable to get anywhere. I have created an `AccountHash` equivalent directly in the `json_comptability` module itself.

2021-01-13 23:25 UTC, darthsiroftardis commented on node/src/types/json_compatibility/contracts.rs
> +        let named_keys = contract
Moved into a helper function called `vectorize` in `json_compatibility`

2021-01-18 10:19 UTC, darthsiroftardis commented
Closing PR. Moved to: https://github.com/CasperLabs/casper-node/pull/772

2021-01-18 10:19 UTC, closed without merging