EE-1141: Hide purse APIs from docs.
CasperLabs/casper-node pull request #754
Opened 2021-01-14 14:40 UTC by mpapierski

Ref: https://casperlabs.atlassian.net/browse/EE-1141

By the way I renamed "getPurseBalance" into "getBalance" in AssemblyScript API, but I didn't hide it in Rust API

2021-01-14 17:20 UTC, henrytill requested changes
Looks good.

I'm creeping the scope here, but I think we probably need to address these other places right now.

1. I think we need to address this so I'll request the change here: rename `get_balance` to `get_purse_balance` and hide it.  Then write a new `get_balance` that doesn't take any arguments and gets the balance of the caller's main purse.

2. Remove transfer to purse from the client.

2021-01-14 17:26 UTC, henrytill commented
Also: hide `system::create_purse` and the AS equivalent.

2021-01-14 22:06 UTC, henrytill approved these changes
Good here.

2021-01-14 22:15 UTC, dwerner commented on client/tests/integration_test.rs
> +                "Invalid arguments to get_transfer_target - must provide either a target account. account=".to_string()).into())
```suggestion
                "Invalid arguments to get_transfer_target - must provide a target account. account=".to_string()).into())
```

2021-01-14 22:19 UTC, dwerner approved these changes

2021-01-15 11:39 UTC, mpapierski commented
bors r+

2021-01-15 13:37 UTC, mpapierski commented
bors r+

2021-01-15 14:13 UTC, merged